-- Main Database Tables

-- Event Schedule tables
DROP TABLE IF EXISTS EventMiscInfo;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS DaySchedule;
DROP TABLE IF EXISTS RosterDate;
DROP TABLE IF EXISTS MemberRoster;

CREATE TABLE IF NOT EXISTS DaySchedule 
(
    DayId INTEGER PRIMARY KEY AUTOINCREMENT, 
    Date TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Event
(
    EventId INTEGER PRIMARY KEY AUTOINCREMENT,
    DayId INTEGER NOT NULL,
    EventTitle TEXT NOT NULL,
    EventTime TEXT NOT NULL,
    EventHost TEXT,
    EventLocation TEXT,
    EventRepeated INTEGER DEFAULT 0,
    FOREIGN KEY (DayId) REFERENCES DaySchedule(DayId)
);

CREATE TABLE IF NOT EXISTS EventMiscInfo
(
    MiscInfoId INTEGER PRIMARY KEY AUTOINCREMENT,
    EventId INTEGER NOT NULL,
    Info TEXT NOT NULL,
    FOREIGN KEY (EventId) REFERENCES Event(EventId)
);

CREATE TABLE IF NOT EXISTS RosterDate
(
    DateId INTEGER PRIMARY KEY AUTOINCREMENT,
    Date TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS MemberRoster
(
    MemberId INTEGER PRIMARY KEY AUTOINCREMENT,
    DateId INTEGER NOT NULL,
    MemberName TEXT NOT NULL,
    MemberRank INTEGER NOT NULL,
    MemberCredits INTEGER NOT NULL,
    MemberDiscordId TEXT NOT NULL, -- DISCORD IDS ARE LARGE
    MemberDateJoined TEXT NOT NULL,
    MemberAltName TEXT,
    MemberDatePromoted TEXT,
    FOREIGN KEY (DateId) REFERENCES RosterDate(DateId)
);